### ISSUE TITLE
The folder named OpenP_W is missing.

### ISSUE THREAD

**Issue by isPANN** [saurabhkhadsang/Virtual-Try-On#1]
Hi there! Your idea is awesome. I was following the instructions in your project and noticed that the folder named "OpenP_W" is missing. Could you please let me know where I can find this folder or if it's missing from the repository? Thank you!

**Comment by saurabhkhadsang** [comment]
Thank you for bringing this to my attention. I apologize for the confusion regarding the missing "OpenP_W" folder in the repository.

The "OpenP_W" folder contains code for generating OpenPose img and JSON files based on input poses. However, I decided to skip including this folder in the repository because the required code can be easily downloaded from official site.

In my case, I used the [Windows Portable Version](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/0_index.md#windows-portable-demo) of OpenPose to generate and save the OpenPose img and JSON files. You can download and install this version to perform the same operations.

 If you have any further questions  with any other aspect of the project, please let me know.
